# -*- coding: utf-8 -*-
"""Inserta narrativas TareasEpo en Cap IV - ancla especifica por contexto previo."""
from docx import Document

doc = Document("INFORME_FINAL_SISTEMA_v2.docx")
paras = doc.paragraphs

# Encontrar EL RF de Cap IV: viene despues de "Nota. Elaboración propia."
anchor_idx = None
for i, p in enumerate(paras):
    t = p.text.strip()
    # El RF de Cap IV esta despues de las figuras/diagramas
    # Identificado por: previo es "Nota. Elaboracion propia." y sig es sobre modulos
    if "Requerimientos Funcionales" in t and p.style.name == "Heading 3":
        prev2 = paras[i-2].text.strip() if i >= 2 else ""
        sig = paras[i+1].text.strip() if i+1 < len(paras) else ""
        if "Elaboraci" in prev2 or "organiz" in sig or "m\u00f3dulos" in sig.lower():
            anchor_idx = i
            print(f"Ancla Cap IV encontrada en [{i}]: '{t}'")
            print(f"  Previo-2: '{prev2[:60]}'")
            print(f"  Sig: '{sig[:60]}'")
            break

if anchor_idx is None:
    # Fallback: indice 649
    anchor_idx = 649
    print(f"Usando ancla fallback [{anchor_idx}]: '{paras[anchor_idx].text[:60]}'")

anchor_para = paras[anchor_idx]

def ins(text, style):
    p = doc.add_paragraph(style=style)
    if text:
        p.add_run(text)
    anchor_para._p.addprevious(p._p)
    return p

def blank():
    ins("", "Normal")

# ===================================================================
ins("Narrativas de Casos de Uso", "Heading 3")
ins("A continuacion se presentan las narrativas detalladas de los casos de uso del "
    "Sistema de Gestion de Tareas - Oficina EPO, describiendo el flujo de interaccion "
    "entre los actores y el sistema para cada funcionalidad principal.", "Body Text")

# --- CS-06: AUTENTICAR USUARIO ---
ins("Narrativa del Caso de Uso CS-06 - Autenticar Usuario", "Heading 3")
ins("Campo/Seccion | Descripcion/Contenido", "Heading 3")
ins("Caso de Uso: CS-06   |   Nombre: Autenticar Usuario   |   Version: 1.0", "Body Text")
ins("Actor: Jefa del CMC / Asistente Administrativo", "Body Text")
ins("Precondicion: Credenciales validas en coleccion 'users' de MongoDB Atlas. Backend activo en Render.", "Body Text")
ins("Postcondicion: JWT generado y almacenado en localStorage. Usuario redirigido al Dashboard.", "Body Text")
ins("Disparador: Acceso a la URL del sistema en Vercel por primera vez o tras cerrar sesion.", "Body Text")
blank()
ins("NARRATIVA PRINCIPAL", "Heading 2")
ins("Accion del Actor | Respuesta del Sistema", "Heading 3")
ins("1. El usuario accede a la URL del sistema desplegado en Vercel.", "Body Text")
ins("El sistema renderiza Login.jsx con formulario de email y contrasena.", "List Paragraph")
ins("2. El usuario ingresa email y contrasena y hace clic en 'Iniciar Sesion'.", "Body Text")
ins("El sistema ejecuta POST /api/auth/login con payload {email, password}.", "List Paragraph")
ins("El backend aplica bcryptjs.compare() para verificar el hash de la contrasena.", "List Paragraph")
ins("El backend verifica que el campo 'activo' del usuario sea true.", "List Paragraph")
ins("El backend genera JWT firmado con payload {id, nombre, rol} y expiracion 7 dias.", "List Paragraph")
ins("3. El sistema retorna respuesta 200 con JWT y datos del usuario.", "Body Text")
ins("El frontend almacena JWT en localStorage con clave 'user'.", "List Paragraph")
ins("AuthContext.jsx actualiza estado global: {id, nombre, email, rol, token}.", "List Paragraph")
ins("PrivateRoute.jsx habilita acceso a todas las rutas protegidas.", "List Paragraph")
ins("React Router DOM redirige a /dashboard.", "List Paragraph")
blank()
ins("POSTCONDICIONES", "Heading 2")
ins("JWT valido en localStorage del navegador.", "Body Text")
ins("Estado de AuthContext cargado con datos del usuario autenticado.", "Body Text")
ins("Todas las rutas protegidas accesibles hasta expiracion del token (7 dias).", "Body Text")
blank()
ins("FLUJOS ALTERNATIVOS", "Heading 2")
ins("FA-01: Credenciales incorrectas - HTTP 401, ToastContext muestra 'Email o contrasena incorrectos'.", "Body Text")
ins("FA-02: Usuario inactivo (activo=false) - HTTP 403, mensaje 'Cuenta desactivada. Contacte al administrador'.", "Body Text")
blank()
ins("FLUJOS DE EXCEPCION", "Heading 2")
ins("FE-01: Backend inactivo/timeout - mensaje 'Error de conexion. Intente nuevamente'.", "Body Text")
ins("FE-02: JWT expirado - AuthContext detecta 401, limpia localStorage y redirige a /login.", "Body Text")
blank()

# --- CS-01: VISUALIZAR DASHBOARD ---
ins("Narrativa del Caso de Uso CS-01 - Visualizar Dashboard", "Heading 3")
ins("Campo/Seccion | Descripcion/Contenido", "Heading 3")
ins("Caso de Uso: CS-01   |   Nombre: Visualizar Dashboard   |   Version: 1.0", "Body Text")
ins("Actor: Jefa del CMC / Asistente Administrativo", "Body Text")
ins("Precondicion: Usuario autenticado con JWT valido en localStorage.", "Body Text")
ins("Postcondicion: Panel principal visible con KPI cards y graficos Recharts cargados.", "Body Text")
ins("Disparador: Acceso a /dashboard tras autenticacion exitosa.", "Body Text")
blank()
ins("NARRATIVA PRINCIPAL", "Heading 2")
ins("Accion del Actor | Respuesta del Sistema", "Heading 3")
ins("1. El usuario accede al Dashboard tras iniciar sesion.", "Body Text")
ins("Layout.jsx renderiza la barra lateral de navegacion y el area principal.", "List Paragraph")
ins("El sistema ejecuta GET /api/tasks/stats con JWT en header Authorization.", "List Paragraph")
ins("2. El backend calcula estadisticas desde la coleccion 'tasks' de MongoDB.", "Body Text")
ins("Total de tareas, tareas pendientes, en progreso, completadas y de alta prioridad.", "List Paragraph")
ins("Agrupacion de tareas por semana para el grafico de barras.", "List Paragraph")
ins("Distribucion de tareas por prioridad para el grafico de dona.", "List Paragraph")
ins("3. El sistema renderiza el Dashboard con los datos recibidos.", "Body Text")
ins("5 tarjetas KPI con contadores en tiempo real.", "List Paragraph")
ins("BarChart de Recharts: tareas completadas por semana.", "List Paragraph")
ins("PieChart de Recharts: distribucion por prioridad (alta/media/baja).", "List Paragraph")
ins("4. El sistema muestra notificaciones recientes.", "Body Text")
ins("GET /api/notifications?limit=5 retorna las ultimas 5 notificaciones.", "List Paragraph")
ins("Badge con conteo de notificaciones no leidas visible en menu lateral.", "List Paragraph")
blank()
ins("POSTCONDICIONES", "Heading 2")
ins("Estadisticas actualizadas reflejando el estado real de MongoDB.", "Body Text")
ins("Graficos Recharts interactivos: tooltip al pasar el cursor.", "Body Text")
ins("Usuario puede navegar a cualquier modulo desde Layout.jsx.", "Body Text")
blank()
ins("FLUJOS ALTERNATIVOS", "Heading 2")
ins("FA-01: Sin tareas registradas - KPI cards en cero, graficos vacios con mensaje explicativo.", "Body Text")
ins("FA-02: Rol Asistente - el menu lateral oculta opciones de administracion.", "Body Text")
blank()
ins("FLUJOS DE EXCEPCION", "Heading 2")
ins("FE-01: Error al cargar stats - skeleton loaders durante carga, Toast de error si falla.", "Body Text")
blank()

# --- CS-02: GESTIONAR TAREAS ---
ins("Narrativa del Caso de Uso CS-02 - Gestionar Tareas", "Heading 3")
ins("Campo/Seccion | Descripcion/Contenido", "Heading 3")
ins("Caso de Uso: CS-02   |   Nombre: Gestionar Tareas   |   Version: 1.0", "Body Text")
ins("Actor Principal: Jefa del CMC. Actor Secundario: Asistente Administrativo.", "Body Text")
ins("Precondicion: Usuario autenticado. Coleccion 'tasks' en MongoDB Atlas.", "Body Text")
ins("Postcondicion: Tarea creada, actualizada o eliminada en MongoDB.", "Body Text")
ins("Disparador: Acceso al modulo /tasks desde el menu lateral.", "Body Text")
blank()
ins("NARRATIVA PRINCIPAL", "Heading 2")
ins("Accion del Actor | Respuesta del Sistema", "Heading 3")
ins("1. El usuario accede al modulo de Tareas.", "Body Text")
ins("GET /api/tasks con JWT recupera todas las tareas de la coleccion.", "List Paragraph")
ins("Tasks.jsx renderiza panel Kanban con columnas: Pendiente, En Progreso, Completada.", "List Paragraph")
ins("Tarjetas muestran: titulo, descripcion, prioridad (color), responsable y fecha limite.", "List Paragraph")
ins("2. La Jefa hace clic en 'Nueva Tarea' y completa el formulario.", "Body Text")
ins("Modal con campos: titulo (requerido), descripcion, prioridad, responsable, fecha limite.", "List Paragraph")
ins("3. La Jefa hace clic en 'Guardar'.", "Body Text")
ins("POST /api/tasks inserta nuevo documento en la coleccion 'tasks'.", "List Paragraph")
ins("El sistema envia notificacion al responsable via POST /api/notifications.", "List Paragraph")
ins("El panel Kanban actualiza mostrando la nueva tarea en la columna 'Pendiente'.", "List Paragraph")
ins("4. El usuario arrastra una tarea a otra columna para cambiar su estado.", "Body Text")
ins("React Beautiful DnD detecta el evento onDragEnd.", "List Paragraph")
ins("PUT /api/tasks/:id actualiza el campo 'estado' y 'updatedAt' en MongoDB.", "List Paragraph")
ins("5. La Jefa elimina una tarea.", "Body Text")
ins("Modal de confirmacion: 'Esta seguro de eliminar esta tarea?'.", "List Paragraph")
ins("DELETE /api/tasks/:id elimina el documento. Kanban se actualiza.", "List Paragraph")
ins("Toast: 'Tarea eliminada exitosamente'.", "List Paragraph")
blank()
ins("Campo/Seccion | Descripcion/Contenido", "Heading 3")
ins("Rutas backend: GET|POST /api/tasks, PUT|DELETE /api/tasks/:id (routes/tasks.js)", "Body Text")
ins("Modelo: Task.js - campos: titulo, descripcion, estado, prioridad, responsable (ObjectId), "
    "fechaLimite, creadoPor, timestamps.", "Body Text")
blank()
ins("POSTCONDICIONES", "Heading 2")
ins("Cambios persistidos en MongoDB Atlas coleccion 'tasks'.", "Body Text")
ins("Historial de cambios trazable mediante timestamps automaticos.", "Body Text")
ins("Responsable asignado recibe notificacion interna.", "Body Text")
blank()
ins("FLUJOS ALTERNATIVOS", "Heading 2")
ins("FA-01: Filtrar tareas por estado, prioridad o responsable - vista Kanban actualizada en tiempo real.", "Body Text")
ins("FA-02: Busqueda textual - filtrado de tarjetas por titulo/descripcion sin recargar.", "Body Text")
ins("FA-03: Editar tarea - modal precargado con datos actuales; PUT /api/tasks/:id al guardar.", "Body Text")
blank()
ins("FLUJOS DE EXCEPCION", "Heading 2")
ins("FE-01: Token expirado - API retorna 401; sesion limpiada, redireccion a /login.", "Body Text")
ins("FE-02: Validacion - titulo vacio o fecha invalida; errores inline en formulario.", "Body Text")
blank()

# --- CS-03: GENERAR REPORTE PDF ---
ins("Narrativa del Caso de Uso CS-03 - Generar Reporte PDF", "Heading 3")
ins("Campo/Seccion | Descripcion/Contenido", "Heading 3")
ins("Caso de Uso: CS-03   |   Nombre: Generar Reporte PDF   |   Version: 1.0", "Body Text")
ins("Actor: Jefa del CMC.", "Body Text")
ins("Precondicion: Usuario autenticado con rol Jefa. Tareas registradas en el periodo seleccionado.", "Body Text")
ins("Postcondicion: Archivo PDF generado y descargado con estadisticas del periodo.", "Body Text")
ins("Disparador: Acceso al modulo /reports y seleccion de periodo mensual.", "Body Text")
blank()
ins("NARRATIVA PRINCIPAL", "Heading 2")
ins("Accion del Actor | Respuesta del Sistema", "Heading 3")
ins("1. La Jefa accede al modulo de Reportes y selecciona mes y anio.", "Body Text")
ins("Reports.jsx renderiza el selector de periodo (mes/anio picker).", "List Paragraph")
ins("2. La Jefa hace clic en 'Generar Reporte'.", "Body Text")
ins("GET /api/reports/monthly?mes=MM&anio=YYYY consulta MongoDB filtrando por periodo.", "List Paragraph")
ins("Backend calcula: total tareas, completadas, pendientes, en progreso, tasa de completitud.", "List Paragraph")
ins("3. El sistema genera el PDF en el cliente con jsPDF.", "Body Text")
ins("jsPDF instancia documento A4 vertical.", "List Paragraph")
ins("jsPDF-autotable genera tabla: N, Titulo, Responsable, Estado, Prioridad, Fecha Limite.", "List Paragraph")
ins("Encabezado del PDF: titulo del reporte, periodo, fecha de generacion, nombre del usuario.", "List Paragraph")
ins("Bloque de KPIs: resumen estadistico del periodo.", "List Paragraph")
ins("4. El PDF se descarga automaticamente.", "Body Text")
ins("doc.save('Reporte_CMC_[mes]_[anio].pdf') activa la descarga en el navegador.", "List Paragraph")
ins("Toast: 'Reporte generado exitosamente'.", "List Paragraph")
blank()
ins("POSTCONDICIONES", "Heading 2")
ins("PDF descargado localmente con nombre 'Reporte_CMC_[mes]_[anio].pdf'.", "Body Text")
ins("Reporte refleja fielmente los datos de MongoDB del periodo.", "Body Text")
ins("Generacion 100% del lado cliente sin carga adicional al servidor.", "Body Text")
blank()
ins("FLUJOS ALTERNATIVOS", "Heading 2")
ins("FA-01: Sin tareas en el periodo - mensaje 'No hay tareas para el periodo seleccionado'.", "Body Text")
ins("FA-02: Vista previa - PDF embebido en iframe antes de descargar.", "Body Text")
blank()
ins("FLUJOS DE EXCEPCION", "Heading 2")
ins("FE-01: Error backend - Toast de error, boton de reintento sin perder seleccion.", "Body Text")
blank()

# --- CS-04: GESTIONAR NOTIFICACIONES ---
ins("Narrativa del Caso de Uso CS-04 - Gestionar Notificaciones", "Heading 3")
ins("Campo/Seccion | Descripcion/Contenido", "Heading 3")
ins("Caso de Uso: CS-04   |   Nombre: Gestionar Notificaciones   |   Version: 1.0", "Body Text")
ins("Actor Principal: Jefa del CMC. Actor Secundario: Asistente (receptor).", "Body Text")
ins("Precondicion: Usuarios autenticados. Coleccion 'notifications' en MongoDB.", "Body Text")
ins("Postcondicion: Notificacion creada, leida o eliminada. Contadores actualizados.", "Body Text")
ins("Disparador: Asignacion de tarea (automatica) o acceso a /notifications.", "Body Text")
blank()
ins("NARRATIVA PRINCIPAL", "Heading 2")
ins("Accion del Actor | Respuesta del Sistema", "Heading 3")
ins("1. El usuario accede al Centro de Notificaciones.", "Body Text")
ins("GET /api/notifications recupera todas las notificaciones del usuario, ordenadas por fecha.", "List Paragraph")
ins("Badge rojo muestra conteo de no leidas. NotificationsCenter.jsx renderiza la lista.", "List Paragraph")
ins("2. El sistema renderiza cada notificacion con tipo, mensaje, fecha y estado.", "Body Text")
ins("Notificaciones no leidas se destacan con fondo diferenciado.", "List Paragraph")
ins("3. El usuario hace clic en una notificacion no leida.", "Body Text")
ins("PATCH /api/notifications/:id/read actualiza 'leida: true' y registra 'fechaLeida'.", "List Paragraph")
ins("El badge decrementa su conteo.", "List Paragraph")
ins("4. La Jefa crea notificacion manual: destinatario, tipo, mensaje.", "Body Text")
ins("POST /api/notifications inserta documento en coleccion 'notifications'.", "List Paragraph")
ins("El destinatario ve el badge incrementado en su proxima carga.", "List Paragraph")
blank()
ins("Campo/Seccion | Descripcion/Contenido", "Heading 3")
ins("Rutas: GET /api/notifications, POST /api/notifications, PATCH /api/notifications/:id/read", "Body Text")
ins("Modelo: Notification.js - campos: destinatario (ObjectId), tipo, mensaje, leida (Boolean), fechaCreacion.", "Body Text")
blank()
ins("POSTCONDICIONES", "Heading 2")
ins("Cambios de estado persistidos en MongoDB.", "Body Text")
ins("Contadores del badge sincronizados con estado real.", "Body Text")
ins("Jefa con trazabilidad de lectura por timestamp.", "Body Text")
blank()
ins("FLUJOS ALTERNATIVOS", "Heading 2")
ins("FA-01: Marcar todas como leidas - PATCH /api/notifications/readAll actualiza todos los documentos.", "Body Text")
ins("FA-02: Eliminar notificacion - DELETE /api/notifications/:id elimina el documento.", "Body Text")
blank()
ins("FLUJOS DE EXCEPCION", "Heading 2")
ins("FE-01: Sin notificaciones - ilustracion y mensaje 'No tienes notificaciones pendientes'.", "Body Text")
blank()

# --- CS-07: ADMINISTRAR DASHBOARD (Estadisticas avanzadas) ---
ins("Narrativa del Caso de Uso CS-07 - Administrar Dashboard", "Heading 3")
ins("Campo/Seccion | Descripcion/Contenido", "Heading 3")
ins("Caso de Uso: CS-07   |   Nombre: Administrar Dashboard   |   Version: 1.0", "Body Text")
ins("Actor: Jefa del CMC.", "Body Text")
ins("Precondicion: Autenticada con rol Jefa. Tareas registradas en la base de datos.", "Body Text")
ins("Postcondicion: Estadisticas avanzadas visualizadas; perfil/usuarios actualizados si aplica.", "Body Text")
ins("Disparador: Acceso al modulo /stats desde el menu lateral.", "Body Text")
blank()
ins("NARRATIVA PRINCIPAL", "Heading 2")
ins("Accion del Actor | Respuesta del Sistema", "Heading 3")
ins("1. La Jefa accede al modulo de Estadisticas.", "Body Text")
ins("Stats.jsx ejecuta en paralelo: GET /api/tasks/stats, GET /api/tasks/byUser, GET /api/tasks/trend.", "List Paragraph")
ins("2. El sistema renderiza el dashboard de estadisticas avanzadas.", "Body Text")
ins("LineChart (Recharts): evolucion de tareas completadas vs. creadas por semana.", "List Paragraph")
ins("StackedBarChart: carga de trabajo por responsable.", "List Paragraph")
ins("PieChart: distribucion por estado y prioridad.", "List Paragraph")
ins("Tabla KPI: tasa de completitud, tiempo promedio de resolucion, responsable mas productivo.", "List Paragraph")
ins("3. La Jefa gestiona cuentas de usuario.", "Body Text")
ins("Tabla de usuarios: nombre, email, rol, activo/inactivo.", "List Paragraph")
ins("Crear usuario: POST /api/auth/register con datos del formulario.", "List Paragraph")
ins("Desactivar cuenta: PUT /api/users/:id con activo=false.", "List Paragraph")
blank()
ins("POSTCONDICIONES", "Heading 2")
ins("Vision completa del rendimiento del area para toma de decisiones.", "Body Text")
ins("Cambios en cuentas de usuario persistidos en MongoDB.", "Body Text")
blank()
ins("FLUJOS ALTERNATIVOS", "Heading 2")
ins("FA-01: Filtrar por rango de fechas personalizado - GET con parametros de inicio/fin.", "Body Text")
ins("FA-02: Exportar estadisticas - generar reporte PDF con los graficos del periodo.", "Body Text")
blank()
ins("FLUJOS DE EXCEPCION", "Heading 2")
ins("FE-01: Email duplicado al crear usuario - HTTP 400 - mensaje 'El email ya esta registrado'.", "Body Text")
blank()

print(f"Narrativas insertadas correctamente en Cap IV.")
print(f"Total parrafos ahora: {len(doc.paragraphs)}")

out = "INFORME_FINAL_SISTEMA_v2.docx"
try:
    doc.save(out)
    print(f"Guardado en {out}")
except PermissionError:
    out = "INFORME_FINAL_SISTEMA_v3.docx"
    doc.save(out)
    print(f"Bloqueado, guardado en {out}")
